# We need to pin here to the same clang version as abseil currently uses to avoid linkage errors.
c_compiler_version:    # [osx]
  - "17"               # [osx]
cxx_compiler_version:  # [osx]
  - "17"               # [osx]

