{% set version = "3.6.1" %}

package:
  name: libprotobuf
  version: {{ version }}

source:
  - url: https://github.com/google/protobuf/archive/v{{ version }}/libprotobuf-v{{ version }}.tar.gz
    sha256: 3d4e589d81b2006ca603c1ab712c9715a76227293032d05b26fca603f90b3f5b
    patches:
      - 4854.patch
      - 0001-remove-Werror-from-test-flags.patch  # [ppc64le]
  # these are git submodules from the 3.6.0 release
  # https://github.com/google/protobuf/tree/v3.6.0/third_party
  - url: https://github.com/google/benchmark/archive/5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8.zip
    sha256: 866d3c8cadb3323251d4fe0e989ea0df51f30660badb73dad0f2d11e5bf1770f
    folder: third_party/benchmark
  - url: https://github.com/google/googletest/archive/c3bb0ee2a63279a803aaad956b9b26d74bf9e6e2.zip
    sha256: 8f282e6bf68956bc40bad8ac9743b9ee5c0bf3cd9a91f830fb5749a5ba8d5f76
    folder: third_party/googletest

build:
  number: 1000
  # Requires C++ 11, VS 2008 is not supported
  skip: True  # [win and vc<14]
  run_exports:
    # breaks backwards compatibility and new SONAME each minor release
    # 3.6.1 also appears to change SONAME from 3.6.0*
    # https://abi-laboratory.pro/tracker/timeline/protobuf/
    - {{ pin_subpackage('libprotobuf', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - unzip  # [not win]
    - make  # [not win]
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a  # [not win]
    - test -f ${PREFIX}/lib/libprotobuf${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1  # [win]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format. C++ Libraries"
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  doc_url: https://developers.google.com/protocol-buffers/
  doc_source_url: https://github.com/google/protobuf/releases

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - wesm
    - hajapy
    - xhochy
