# keep this without major version to let the bot pick it up
{% set version = "22.5" %}
# protobuf doesn't add the major version in the tag, it's defined per language in
# https://github.com/protocolbuffers/protobuf/blob/main/version.json
{% set major = "4" %}

{% set libraries = ["libprotoc", "libprotobuf", "libprotobuf-lite"] %}

package:
  name: libprotobuf-split
  version: {{ major ~ "." ~ version }}

source:
  - url: https://github.com/protocolbuffers/protobuf/archive/refs/tags/v{{ version.replace(".rc", "-rc") }}.tar.gz
    sha256: 4b98c800b352e7582bc92ed398999030ce4ebb49c7858dcb070850ec476b72f2
    patches:
      - patches/0001-use-consistent-cmake-location.patch
      - patches/0002-set-static-lib-extension-on-windows.patch
      # backport https://github.com/protocolbuffers/protobuf/pull/12577
      - patches/0003-Enable-the-selection-of-system-provided-jsoncpp-1257.patch
      - patches/0004-always-look-for-shared-abseil-builds.patch

build:
  number: 0

outputs:
  - name: libprotobuf
    script: build-lib.sh   # [unix]
    script: build-lib.bat  # [win]
    build:
      run_exports:
        # breaks backwards compatibility and new SONAME each minor release
        # https://abi-laboratory.pro/tracker/timeline/protobuf/
        # One exception was that 3.6.1 was incompatible with 3.6.0
        - {{ pin_subpackage('libprotobuf', max_pin='x.x') }}
      ignore_run_exports_from:
        - jsoncpp
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - gtest
        - jsoncpp
        - libabseil
        # requires abseil test targets to build with tests enabled
        - libabseil-tests
        - zlib
      run:
        - ucrt  # [win]
    test:
      requires:
        # cmake needs compiler to be able to run package detection, see
        # https://discourse.cmake.org/t/questions-about-find-package-cli-msvc/6194
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      files:
        - cmake_test/
      commands:
        {% for each_lib in libraries %}
        # shared libraries
        - test -f ${PREFIX}/lib/{{ each_lib }}.so                      # [linux]
        - test -f ${PREFIX}/lib/{{ each_lib }}.dylib                   # [osx]
        - if not exist %LIBRARY_BIN%\{{ each_lib }}.dll exit 1         # [win]
        - if not exist %LIBRARY_LIB%\{{ each_lib }}.lib exit 1         # [win]

        # absence of static libraries
        - test ! -f ${PREFIX}/lib/{{ each_lib }}.a                     # [unix]
        - if exist %LIBRARY_LIB%\{{ each_lib }}-static.lib exit 1      # [win]
        {% endfor %}

        # cmake
        - test -f ${PREFIX}/lib/cmake/protobuf/protobuf-config.cmake              # [unix]
        - if not exist %LIBRARY_LIB%\cmake\protobuf\protobuf-config.cmake exit 1  # [win]

        # pkgconfig
        - test -f ${PREFIX}/lib/pkgconfig/protobuf.pc                   # [unix]
        - test -f ${PREFIX}/lib/pkgconfig/protobuf-lite.pc              # [unix]
        - if not exist %LIBRARY_LIB%\pkgconfig\protobuf.pc exit 1       # [win]
        - if not exist %LIBRARY_LIB%\pkgconfig\protobuf-lite.pc exit 1  # [win]

        # binary
        - protoc --help

        # more CMake integration (CMake uses its own FindProtobuf)
        - cd cmake_test
        - cmake -GNinja $CMAKE_ARGS .   # [unix]
        - cmake -GNinja %CMAKE_ARGS% .  # [win]

  - name: libprotobuf-static
    script: build-lib.sh   # [unix]
    script: build-lib.bat  # [win]
    build:
      ignore_run_exports_from:
        - jsoncpp
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - gtest
        - jsoncpp
        - libabseil
        - libabseil-tests
        - zlib
        - {{ pin_subpackage('libprotobuf', exact=True) }}
      run:
        - {{ pin_subpackage('libprotobuf', exact=True) }}
    test:
      requires:
        # cmake needs compiler to be able to run package detection, see
        # https://discourse.cmake.org/t/questions-about-find-package-cli-msvc/6194
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      files:
        - cmake_test/
      commands:
        {% for each_lib in libraries %}
        # static libraries
        - test -f ${PREFIX}/lib/{{ each_lib }}.a                       # [unix]
        - if not exist %LIBRARY_LIB%\{{ each_lib }}-static.lib exit 1  # [win]
        {% endfor %}

        # more CMake integration (CMake uses its own FindProtobuf)
        - cd cmake_test
        - cmake -GNinja $CMAKE_ARGS .   # [unix]
        - cmake -GNinja %CMAKE_ARGS% .  # [win]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers - Google's data interchange format. C++ Libraries and protoc, the protobuf compiler.
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  dev_url: https://github.com/protocolbuffers/protobuf
  doc_url: https://developers.google.com/protocol-buffers/
  doc_source_url: https://github.com/protocolbuffers/protobuf/releases

extra:
  recipe-maintainers:
    - xylar
    - dopplershift
    - jakirkham
    - ocefpaf
    - wesm
    - hajapy
    - xhochy
    - h-vetinari
  feedstock-name: libprotobuf
