{% set name = "libprotobuf" %}
{% set version = "3.6.0.1" %}
{% set sha256 = "1144ef1fa9c50d3c04880f363b988df6ca6a66e337a945f1661cf4256ffba749" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/google/protobuf/archive/v{{ version }}/protobuf-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - cmake              # [win]
    - autoconf           # [unix]
    - automake           # [unix]
    - libtool            # [unix]
    - pkg-config         # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - git                # [win]
    - zlib
    - unzip              # [unix]
  run:
    - zlib

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
    - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME                   # [unix]
    - conda inspect objects -p $PREFIX $PKG_NAME                    # [osx]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format. C++ Libraries"

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - wesm
    - hajapy
