appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cvzJDC7coxHsDe6x3i9L/7Cg1N36+I9fOGjnwK+gjkSmkzplJuqJ11JuY+EpI0pfTjiIhDcIvvRWX+BQBrxh4wyGlC0G9PofsCdnOKkfXNuJQoWGByWwzwpMHcujmz52dQXcu10J26qpmE2e4HXga4laoq0YTDeOGRKRWvXnq7HYuLvsM//g1oCSqLqdK+KJlNWG3oLKT6ulAA/IRwm46D5j0lCRX0KoqqsZxd9efXHFzrz6lRRZgpAqTlbXaIjr2jxipAMiwDNg9JHEqSiZ0rDO8PuVN1M6Ho823vOFi8mUVySyD9OIJqEizA+lFxiFxRLDBowfEdoP/Nz+UuezgvD4LZr04qHTggwiytjwU4pU/9QPipZHPV/ZPKwyt1hWnAQgCyF5PJTa4SS2hCR60UkOKDOQGPzwVYgpaNj+ga/u0gC32OV5e2cq4yqf3PAEd6RMb2toBwZOb+iBAq+QDQxrScKU42BZWCizjxss8bSjajcJA/3pGbVtbuuthu2iSUCt1lnzig9s4nyabgMG7eyDTUTl0Db49Nd4EuAOjgXaAJj3pzkhpGFicpaJxTANa1MWj6lUnomKugaei+tSbWuViOAk/WYr5yMnPsREVP5oB60WQcb6RNWa9ks00YzcHuO1wwI/hWoz3HbDCD4GKb45HBONtQ1WZdKezZwKcVE=}
